version: '3.3'
services:
   db:
    container_name: mestre_pokemon
    image: mysql:8.0.23
    platform: linux/x86_64
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: senha
volumes:
  my-db: